name: pusher_dart
description: Unofficial pusher client for dart
version: 0.2.0+1
author: "Prabhakar Bhat <prabhakarbhat@live.com>"
homepage: https://github.com/jaysson/pusher_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.0.0
  http: ^0.13.1
  meta: ^1.3.0